version: "3"
services:
  node-boilerplate:
    build: .
    command: npm run start
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/node-es8-boilerplate
      - PORT=8000
      - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy4
      - JWT_EXPIRATION_MINUTES=15
      - MONGO_URI=mongodb://localhost:27017/express-es8
      - MONGO_URI_TEST=mongodb://localhost:27017/express-es8
      - RATE_LIMIT_TIME=15
      - RATE_LIMIT_REQUEST=15
    volumes:
      - .:/app
    ports:
      - "80:8000"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"